// Sync
export const REFRESH_STYLESHEET_STATUS = 'REFRESH_STYLESHEET_STATUS';

// Async
export const FETCH_VIDEOS_REQUESTED = 'FETCH_VIDEOS_REQUESTED';
export const FETCH_VIDEOS_SUCCEEDED = 'FETCH_VIDEOS_SUCCEEDED';
export const FETCH_VIDEOS_FAILED = 'FETCH_VIDEOS_FAILED';
