// Sync
export const REFRESH_STYLESHEET_STATUS = 'REFRESH_STYLESHEET_STATUS';

export const UPDATE_PLAYER = 'UPDATE_PLAYER';


// Async
export const FETCH_SPOTIFY_TOKEN_REQUESTED = 'FETCH_SPOTIFY_ACCESS_REQUESTED';
export const FETCH_SPOTIFY_TOKEN_SUCCEEDED = 'FETCH_SPOTIFY_ACCESS_SUCCEEDED';
export const FETCH_SPOTIFY_TOKEN_FAILED = 'FETCH_SPOTIFY_TOKEN_FAILED';

export const FETCH_INITIAL_ARTIST_SUCCEEDED = 'FETCH_INITIAL_ARTIST_SUCCEEDED';
export const FETCH_INITIAL_ARTIST_FAILED = 'FETCH_INITIAL_ARTIST_FAILED';

export const DETERMINE_SIMILAR_ARTISTS_REQUESTED = 'DETERMINE_SIMILAR_ARTISTS_REQUESTED';
export const DETERMINE_SIMILAR_ARTISTS_SUCCEEDED = 'DETERMINE_SIMILAR_ARTISTS_SUCCEEDED';
export const DETERMINE_SIMILAR_ARTISTS_FAILED = 'DETERMINE_SIMILAR_ARTISTS_FAILED';

export const FETCH_VIDEOS_REQUESTED = 'FETCH_VIDEOS_REQUESTED';
export const FETCH_VIDEOS_SUCCEEDED = 'FETCH_VIDEOS_SUCCEEDED';
export const FETCH_VIDEOS_FAILED = 'FETCH_VIDEOS_FAILED';

export const SELECT_VIDEO_REQUESTED = 'SELECT_VIDEO_REQUESTED';
export const SELECT_VIDEO_SUCCEEDED = 'SELECT_VIDEO_SUCCEEDED';
export const SELECT_VIDEO_FAILED = 'SELECT_VIDEO_FAILED';

export const ADD_TO_BLACKLIST_REQUESTED = 'ADD_TO_BLACKLIST_REQUESTED';
export const ADD_TO_BLACKLIST_SUCCEEDED = 'ADD_TO_BLACKLIST_SUCCEEDED';
export const ADD_TO_BLACKLIST_FAILED = 'ADD_TO_BLACKLIST_FAILED';
